.editorconfig, .gitattributes, .gitignore, .prettierignore, .prettierrc, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, LICENSE, README.md, gatsby/gatsby-config.js, gatsby/gatsby-node.js, gatsby/package-lock.json, gatsby/package.json, gatsby/src/pages/index.js
https://nicedigital.atlassian.net/browse/CKS-231
=> CKS-231 Project setup

.vscode/launch.json, gatsby/gatsby-config.js, gatsby/package-lock.json, gatsby/package.json, gatsby/src/pages/index.js, gatsby/src/pages/index.tsx, gatsby/tsconfig.json
https://nicedigital.atlassian.net/browse/CKS-252
=> CKS-252 Setup TypeScript

.vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, README.md, gatsby/.prettierrc, gatsby/jest.config.js, gatsby/jest.setup.ts, gatsby/package-lock.json, gatsby/package.json, gatsby/src/pages/__tests__/__snapshots__/index.test.tsx.snap, gatsby/src/pages/__tests__/index.test.tsx, gatsby/src/pages/index.tsx, gatsby/tsconfig.json
https://nicedigital.atlassian.net/browse/CKS-254
=> CKS-254 Set up Jest tests

.gitignore, .vscode/launch.json, .vscode/settings.json, gatsby/gatsby-config.js, gatsby/gatsby-node.js, gatsby/package-lock.json, gatsby/package.json, gatsby/plugins/gatsby-source-cks/gatsby-node.js, gatsby/plugins/gatsby-source-cks/package.json, gatsby/plugins/gatsby-source-cks/src/constants.ts, gatsby/plugins/gatsby-source-cks/src/gatsby-node.ts, gatsby/plugins/gatsby-source-cks/src/schema.ts, gatsby/plugins/gatsby-source-cks/src/types.d.ts, gatsby/src/gatsby-node.ts, gatsby/src/graphql-fragments/FullTopic.ts, gatsby/src/graphql-fragments/PartialTopic.ts, gatsby/src/pages/index.tsx, gatsby/src/templates/Topic/Topic.tsx, gatsby/src/types.d.ts, gatsby/tsconfig.json
https://nicedigital.atlassian.net/browse/CKS-255
=> CKS-255 Scaffold source plugin

web-app/CKS.Web/Startup.cs
https://nicedigital.atlassian.net/browse/CKS-238
This serves index.html as the default file
=> CKS-238 Add default files to web app startup

web-app/CKS.Web.Test/CKS.Web.Test.csproj, web-app/CKS.Web.Test/IntegrationTests/Infrastructure/CKSWebApplicationFactory.cs, web-app/CKS.Web.Test/IntegrationTests/Infrastructure/TestBase.cs, web-app/CKS.Web.Test/IntegrationTests/SearchTests.cs, web-app/CKS.Web.Test/UnitTests/Controllers/SearchControllerTests.cs, web-app/CKS.sln, web-app/README.md
https://nicedigital.atlassian.net/browse/CKS-258
=> CKS-258 Setup xUnit tests

gatsby/plugins/gatsby-source-cks/src/__tests__/__snapshots__/gatsby-node.test.ts.snap
https://nicedigital.atlassian.net/browse/CKS-250
=> CKS-250 Fix broken test

gatsby/plugins/gatsby-source-cks/src/node-types.ts
https://nicedigital.atlassian.net/browse/CKS-250
=> CKS-250 Fix wrong node type

.editorconfig, .vscode/settings.json, functional-tests/features/aboutPage.feature, functional-tests/features/developmentPage.feature, functional-tests/features/homepage.feature, functional-tests/features/searchPage.feature, functional-tests/features/specialitiesListPage.feature, functional-tests/features/specialitiesPage.feature, functional-tests/features/specialityPage.feature, functional-tests/features/topicPage.feature, functional-tests/features/topicsListPage.feature, functional-tests/features/topicsPage.feature, functional-tests/features/whatsNewPage.feature, functional-tests/wdio.conf.js, gatsby/src/gatsby-node.ts, gatsby/src/graphql-fragments/FullSpeciality.ts, gatsby/src/graphql-fragments/PartialSpeciality.tsx, gatsby/src/pages/about.tsx, gatsby/src/pages/development.tsx, gatsby/src/pages/search.tsx, gatsby/src/pages/specialities.tsx, gatsby/src/pages/topics.tsx, gatsby/src/pages/whatsNew.tsx, gatsby/src/templates/Speciality/Speciality.tsx, gatsby/src/types.d.ts
https://nicedigital.atlassian.net/browse/CKS-277
=> CKS-277 Scafold pages and accessibility tests

gatsby/__mocks__/gatsby.js, gatsby/gatsby-node.js, gatsby/jest.config.js, gatsby/jest.setup.ts, gatsby/package-lock.json, gatsby/package.json, gatsby/src/components/Footer/Footer.test.tsx, gatsby/src/components/Footer/Footer.tsx, gatsby/src/components/Footer/GlobalNavFooter.ts, gatsby/src/components/Header/GlobalNavHeader.ts, gatsby/src/components/Header/Header.test.tsx, gatsby/src/components/Header/Header.tsx, gatsby/src/components/Layout/Layout.test.tsx, gatsby/src/components/Layout/Layout.tsx, gatsby/src/pages/__tests__/__snapshots__/index.test.tsx.snap, gatsby/src/pages/__tests__/index.test.tsx, gatsby/tsconfig.json, gatsby/types.d.ts, gatsby/utils/test-utils.tsx
https://nicedigital.atlassian.net/browse/CKS-275
=> CKS-275 Add global nav header and footer

web-app/CKS.Web/web.config, web-app/README.md
https://nicedigital.atlassian.net/browse/CKS-316
=> CKS-316 Add compression

.gitignore, web-app/CKS.Web/CKS.Web.csproj, web-app/CKS.Web/Controllers/ErrorTestController.cs, web-app/CKS.Web/Program.cs, web-app/CKS.Web/SeriLogger.cs, web-app/CKS.Web/appsettings.json
https://nicedigital.atlassian.net/browse/CKS-288
=> CKS-288 Add NICE Logging

gatsby/static/robots.txt
https://nicedigital.atlassian.net/browse/CKS-237
=> CKS-237 Add Robots.txt

gatsby/plugins/gatsby-source-cks/src/node-creation/__tests__/specialities.test.ts, gatsby/plugins/gatsby-source-cks/src/node-creation/__tests__/topics.test.ts, gatsby/plugins/gatsby-source-cks/src/node-creation/specialities.ts, gatsby/plugins/gatsby-source-cks/src/node-creation/topics.ts
https://nicedigital.atlassian.net/browse/CKS-320
=> CKS-320 Remove commas from slugs

web-app/CKS.Web/CKS.Web.csproj
Update search client to fix failing builds
=> Update search client

gatsby/gatsby-browser.js
Using requestAnimationFrame
https://nicedigital.atlassian.net/browse/CKS-348
=> CKS-348 Delay GTM data layer page view push

functional-tests/features/404.feature, functional-tests/features/aboutPage.feature, functional-tests/features/header.feature, functional-tests/steps/then.js, functional-tests/steps/when.js, functional-tests/support/action/typeInSearchBox.js, functional-tests/support/selectors/common.js, functional-tests/support/selectors/index.js, gatsby/declaration.d.ts, gatsby/src/pages/about/__snapshots__/index.test.tsx.snap, gatsby/src/pages/about/index.module.scss, gatsby/src/pages/about/index.test.tsx, gatsby/src/pages/about/index.tsx, web-app/CKS.Web/Startup.cs
https://nicedigital.atlassian.net/browse/CKS-243
=> CKS-243 About page

functional-tests/features/specialitiesListPage.feature, functional-tests/features/specialityPage.feature, gatsby/__mocks__/gatsby.js, gatsby/src/components/ColumnList/ColumnList.module.scss, gatsby/src/components/ColumnList/ColumnList.test.tsx, gatsby/src/components/ColumnList/ColumnList.tsx, gatsby/src/pages/__tests__/specialities.test.tsx, gatsby/src/pages/specialities.tsx, gatsby/src/templates/Speciality/Speciality.test.tsx, gatsby/src/templates/Speciality/Speciality.tsx
https://nicedigital.atlassian.net/browse/CKS-242
=> CKS-242 Specialities list page and speciality pages

functional-tests/features/404.feature, functional-tests/features/aboutPage.feature, functional-tests/features/developmentPage.feature, functional-tests/features/header.feature, functional-tests/features/homepage.feature, functional-tests/features/specialitiesListPage.feature, functional-tests/features/specialityPage.feature, functional-tests/features/tagManager.feature, functional-tests/features/topicPage.feature, functional-tests/features/topicsListPage.feature, functional-tests/features/whatsNewPage.feature, functional-tests/steps/given.js, functional-tests/steps/when.js, functional-tests/support/action/closeGlobalNavCookieMessage.js, functional-tests/support/action/closeGlobalNavCovidMessage.js, functional-tests/support/action/scrollInToView.js, functional-tests/support/action/waitForTitleToChange.js, functional-tests/support/pagePaths.js, functional-tests/wdio.conf.js
https://nicedigital.atlassian.net/browse/CKS-362
=> CKS-362 Fix flakey tests

gatsby/src/components/SEO/SEO.tsx, gatsby/src/pages/index.tsx, gatsby/static/BingSiteAuth.xml
https://nicedigital.atlassian.net/browse/CKS-235
=> CKS-235 Webmaster tools verification 

functional-tests/steps/given.js, gatsby/src/components/Footer/Footer.tsx, gatsby/src/components/Footer/GlobalNavFooter.ts, gatsby/src/components/Header/GlobalNavHeader.ts, gatsby/src/components/Header/Header.tsx
https://nicedigital.atlassian.net/browse/CKS-307
Remove the lazy loading work around which was a temp fix for https://github.com/alphagov/accessible-autocomplete/issues/433
=> CKS-307 Render GN as part of static site

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-307
=> CKS-307 Bump global/autocomplete version

gatsby/gatsby-config.js, gatsby/plugins/gatsby-source-cks/src/api/api.test.ts, gatsby/plugins/gatsby-source-cks/src/api/api.ts, gatsby/src/components/Header/Header.test.tsx, gatsby/src/components/Header/Header.tsx, gatsby/src/pages/__tests__/whats-new.test.tsx, gatsby/src/pages/topics.tsx
https://nicedigital.atlassian.net/browse/CKS-374
=> CKS-374 Fix linting

gatsby/src/components/Header/Header.test.tsx
Fixing broken test from #59 
https://nicedigital.atlassian.net/browse/CKS-374
=> CKS-374 Fix test hotfix

gatsby/src/pages/__tests__/specialities.test.tsx, gatsby/src/pages/specialities.tsx
https://nicedigital.atlassian.net/browse/CKS-359
=> CKS-359 Add full stop to specialties lead para

gatsby/src/pages/search.module.scss, gatsby/src/pages/search.tsx
https://nicedigital.atlassian.net/browse/CKS-379
=> CKS-379 Fix search list margin issue

functional-tests/features/404.feature, gatsby/src/pages/404.tsx, gatsby/src/pages/__tests__/404.test.tsx, gatsby/src/pages/__tests__/__snapshots__/404.test.tsx.snap
https://nicedigital.atlassian.net/browse/CKS-233
=> CKS-233 Update 404 page

gatsby/package-lock.json, gatsby/package.json
Which in turn includes smaller logo SVG
=> CKS-000 Bump global nav version

.vscode/tasks.json, functional-tests/features/homepage.feature, functional-tests/support/action/waitForUrlToChange.js
https://nicedigital.atlassian.net/browse/CKS-386
=> CKS-386 Fix flakey test

gatsby/src/pages/__tests__/index.test.tsx, gatsby/src/pages/index.tsx
https://nicedigital.atlassian.net/browse/CKS-394
=> CKS-394 Update homepage copy

gatsby/src/components/TopicChaptersMenu/TopicChaptersMenu.test.tsx, gatsby/src/gatsby-node.ts, gatsby/src/templates/ChapterLevel1/ChapterLevel1.test.tsx, gatsby/src/templates/ChapterLevel1/ChapterLevel1.tsx, gatsby/src/templates/ChapterLevel2/ChapterLevel2.test.tsx, gatsby/src/templates/ChapterLevel2/ChapterLevel2.tsx, gatsby/src/types.d.ts
https://nicedigital.atlassian.net/browse/CKS-392
=> CKS-392 Add last revised date to all chapter pages

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-393
=> CKS-393 Update global nav version

gatsby/src/components/ChapterContents/ChapterContents.module.scss, gatsby/src/templates/Topic/Topic.module.scss, gatsby/src/templates/Topic/Topic.tsx
https://nicedigital.atlassian.net/browse/CKS-367
Follow up to #89
=> CKS-367 Change topic landing page links to horizontal

gatsby/plugins/gatsby-source-cks/src/link-rewriter/index.test.ts, gatsby/plugins/gatsby-source-cks/src/link-rewriter/index.ts, gatsby/plugins/gatsby-source-cks/src/link-rewriter/link-regexes.ts, gatsby/plugins/gatsby-source-cks/src/link-rewriter/node-model-extensions.ts
https://nicedigital.atlassian.net/browse/CKS-404
=> CKS-404 Fix broken links

gatsby/plugins/gatsby-source-cks/src/node-creation/__tests__/topics.test.ts, gatsby/plugins/gatsby-source-cks/src/node-creation/chapters.ts, gatsby/plugins/gatsby-source-cks/src/node-creation/specialities.ts, gatsby/plugins/gatsby-source-cks/src/node-creation/topics.ts, gatsby/plugins/gatsby-source-cks/src/utils/index.ts, gatsby/static/.htaccess
https://nicedigital.atlassian.net/browse/CKS-406
=> CKS-406 Slashes in topic names and redirects

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-417
=> CKS-417 Bump global nav version

web-app/CKS.Web/Middleware/SecurityHeadersMiddleware.cs
https://nicedigital.atlassian.net/browse/CKS-342
=> CKS-342 Add CSP header

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-420
Includes collapsed covid-19 banner
=> CKS-420 Update global nav to latest version

gatsby/package-lock.json, gatsby/package.json
Release change to global nav menu button
=> CKS-434 Update global nav to latest commit

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-290
=> CKS-290 Add teamcity audit reporting

functional-tests/README.md, functional-tests/docker-compose.yml, functional-tests/docker-run.sh, functional-tests/features/searchPage.feature, functional-tests/package-lock.json, functional-tests/package.json, functional-tests/steps/given.js, functional-tests/support/action/acceptCookieBanner.js, functional-tests/support/action/closeGlobalNavCookieMessage.js, functional-tests/support/action/closeGlobalNavCovidMessage.js, functional-tests/support/action/scrollInToView.js, functional-tests/support/pagePaths.js, gatsby/src/components/Header/Header.tsx, gatsby/src/components/Layout/Layout.tsx
https://nicedigital.atlassian.net/browse/CKS-419
=> CKS-419 Add cookie banner

web-app/CKS.Web/CKS.Web.csproj
https://nicedigital.atlassian.net/browse/CKS-414
=> CKS-414 Search client upgrade & .Net Standard

gatsby/src/pages/__tests__/specialities.test.tsx, gatsby/src/pages/__tests__/topics.test.tsx, gatsby/src/pages/about/__tests__/__snapshots__/index.test.tsx.snap, gatsby/src/pages/about/index.tsx, gatsby/src/pages/index.tsx, gatsby/src/pages/specialities.tsx, gatsby/src/pages/topics.tsx
And change number of topics from 350 to 370
https://nicedigital.atlassian.net/browse/CKS-455
=> CKS-455 Fix spelling mistakes

web-app/CKS.Web.Test/UnitTests/Controllers/SearchControllerTests.cs, web-app/CKS.Web/Controllers/SearchController.cs
https://nicedigital.atlassian.net/browse/CKS-364
=> CKS-364 Change number of results per page to 15

README.md, fake-api/README.md, fake-api/index.js, gatsby/gatsby-config.js
https://nicedigital.atlassian.net/browse/CKS-461
=> CKS-461 Change port of fake-api and update readme

web-app/CKS.Web/CKS.Web.csproj
https://nicedigital.atlassian.net/browse/CKS-450
=> CKS-450 Search client update: beta elastic search option added

gatsby/src/components/ChapterBody/ChapterBody.module.scss
https://nicedigital.atlassian.net/browse/CKS-412
=> CKS-412 Show basis for recommendation for print

gatsby/src/components/Lato/Lato.tsx, gatsby/src/components/Layout/Layout.tsx
https://nicedigital.atlassian.net/browse/CKS-485
=> CKS-485 Make render blocking resources async

functional-tests/fake-elastic/data/autocomplete/cancer.json, functional-tests/features/topicsListPage.feature, functional-tests/steps/then.ts, gatsby/src/pages/__tests__/topics.test.tsx, gatsby/src/pages/topics.module.scss, gatsby/src/pages/topics.tsx
We have the docked one instead
https://nicedigital.atlassian.net/browse/CKS-470
=> CKS-470 Remove back to top from topic list page

functional-tests/package-lock.json, functional-tests/package.json, gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-517
=> CKS-517 Fix audit issues

gatsby/gatsby-browser.ts
https://nicedigital.atlassian.net/browse/CKS-512
=> CKS-512 Stop hash changes tracking as page views

functional-tests/Dockerfile
https://nicedigital.atlassian.net/browse/CKS-341
=> CKS-341 Use alpine linux for test runner

gatsby/src/components/Layout/_tables.scss
https://nicedigital.atlassian.net/browse/CKS-523
=> CKS-523 Fix table scroll

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-542
=> CKS-542 Bump global nav

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-551
=> CKS-551 Update GN with fix for tablet clipping

web-app/CKS.Web.Test/IntegrationTests/CookieSyncTests.cs, web-app/CKS.Web.Test/IntegrationTests/Infrastructure/CKSWebApplicationFactory.cs, web-app/CKS.Web/Controllers/CookieSyncController.cs
https://nicedigital.atlassian.net/browse/CKS-467
=> CKS-467 Add cookie sync endpoint

web-app/CKS.Web/CKS.Web.csproj
https://nicedigital.atlassian.net/browse/CKS-559
=> CKS Search Client Update

gatsby/gatsby-config.js, gatsby/src/components/TopicChaptersMenu/TopicChaptersMenu.module.scss, gatsby/src/components/TopicChaptersMenu/TopicChaptersMenu.test.tsx, gatsby/src/components/TopicChaptersMenu/TopicChaptersMenu.tsx
https://nicedigital.atlassian.net/browse/CKS-565
=> CKS-565 Fix CLS issue with mobile nav

gatsby/src/pages/about/__tests__/__snapshots__/index.test.tsx.snap, gatsby/src/pages/about/index.tsx
https://nicedigital.atlassian.net/browse/CKS-583
=> CKS-583 Update text on about page

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/NAV-12
=> NAV-12 Bump global nav version to include life sciences link

web-app/CKS.Web/Controllers/CookieSyncController.cs
https://nicedigital.atlassian.net/browse/CKS-606
=> CKS-606 Update cookie to include GA4 cookies

functional-tests/features/searchPage.feature
https://nicedigital.atlassian.net/browse/CKS-610
=> CKS-610 Update flakey test

gatsby/src/components/ChapterBody/ChapterBody.tsx
https://nicedigital.atlassian.net/browse/CKS-614
=> CKS-614 Fix basis tracking

functional-tests/steps/when.ts, functional-tests/support/action/isAtTopOfScreen.ts, functional-tests/support/action/scrollInToView.ts, functional-tests/support/action/waitForScrollToElement.ts, gatsby/gatsby-ssr.tsx, gatsby/package-lock.json, gatsby/package.json, gatsby/src/components/Header/Header.test.tsx
https://nicedigital.atlassian.net/browse/CKS-613
=> CKS-613 Bump global nav to use meganav

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-589
=> CKS-589 Update web vitals library

gatsby/package-lock.json, gatsby/package.json, gatsby/src/pages/search.tsx
https://nicedigital.atlassian.net/browse/CKS-601
=> CKS-601 Remove evidence from no results

gatsby/src/pages/search.tsx
https://nicedigital.atlassian.net/browse/CKS-626
=> CKS-626 Replace links to new BNF search URL

functional-tests/features/searchPage.feature, gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-645
=> CKS-645 Bump GN version for advice word

gatsby/src/pages/about/__tests__/__snapshots__/index.test.tsx.snap, gatsby/src/pages/about/index.tsx
https://nicedigital.atlassian.net/browse/CKS-648
=> CKS-648 Update name for clarity

functional-tests/features/searchPage.feature, gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-652
=> CKS-652 Update list spacing

functional-tests/features/searchPage.feature, gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-664
=> CKS-664 GN version bump

gatsby/src/pages/search.tsx
https://nicedigital.atlassian.net/browse/CKS-672
=> CKS-672 Fix no results link to guidance search

fake-api/index.js, functional-tests/features/aboutPage.feature, functional-tests/package-lock.json, functional-tests/package.json, functional-tests/support/action/scrollInToView.ts, functional-tests/tsconfig.json, functional-tests/wdio.conf.ts
- Upgraded webdriver to v8
- Upgraded to latest nice-digital/wdio-cucumber-steps
=> upgraded to wdio v8

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-682
=> CKS-682 Version bump global-nav

functional-tests/Dockerfile, functional-tests/package-lock.json, functional-tests/package.json
Updated some packages to fix the allure reports not showing in TeamCity
=> upgrade packages to fix allure reports

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-690
=> CKS-690 Version bump GN

gatsby/src/components/Layout/Layout.module.scss, gatsby/src/components/Layout/Layout.test.tsx, gatsby/src/components/Layout/Layout.tsx, gatsby/src/components/Layout/__snapshots__/Layout.test.tsx.snap
https://nicedigital.atlassian.net/browse/CKS-684
=> CKS-684 Add EULA panel to all pages

gatsby/package-lock.json, gatsby/package.json, gatsby/src/components/HelpPanel/__snapshots__/HelpPanel.test.tsx.snap, gatsby/src/components/Layout/__snapshots__/Layout.test.tsx.snap, gatsby/src/pages/__tests__/__snapshots__/404.test.tsx.snap, gatsby/src/pages/about/__tests__/__snapshots__/development.test.tsx.snap, gatsby/src/pages/about/__tests__/__snapshots__/index.test.tsx.snap
https://nicedigital.atlassian.net/browse/CKS-695
=> CKS-695 Update design system version

gatsby/src/components/HelpPanel/HelpPanel.tsx, gatsby/src/components/HelpPanel/__snapshots__/HelpPanel.test.tsx.snap, gatsby/src/pages/about/__tests__/__snapshots__/development.test.tsx.snap, gatsby/src/pages/about/__tests__/__snapshots__/index.test.tsx.snap, gatsby/src/pages/about/development.tsx
https://nicedigital.atlassian.net/browse/CKS-700
=> CKS-700 Update get-involved links

gatsby/package-lock.json, gatsby/package.json, gatsby/src/components/SiteHeader/SiteHeader.test.tsx
https://nicedigital.atlassian.net/browse/CKS-716
=> CKS-716 Master version bump GN

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-720
=> CKS-720 Bump GN version

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-615
=> CKS-615 npm audit minimal

.vscode/launch.json, .vscode/settings.json, functional-tests/features/searchPage.feature, functional-tests/steps/given.ts, functional-tests/support/action/acceptEULA.ts, gatsby/gatsby-ssr.tsx, gatsby/package-lock.json, gatsby/package.json, gatsby/src/components/EULABanner/EULABanner.module.scss, gatsby/src/components/EULABanner/EULABanner.test.tsx, gatsby/src/components/EULABanner/EULABanner.tsx, gatsby/src/components/EULABanner/__snapshots__/EULABanner.test.tsx.snap, gatsby/src/components/Layout/Layout.tsx
https://nicedigital.atlassian.net/browse/CKS-714
=> CKS-714 EULA banner

gatsby/src/components/SiteHeader/SiteHeader.test.tsx
https://nicedigital.atlassian.net/browse/CKS-722
=> CKS-722 Update SiteHeader unit test to fix intermittent TC build failure

gatsby/gatsby-config.js, gatsby/package-lock.json, gatsby/package.json, gatsby/src/components/SEO/SEO.tsx, gatsby/src/components/SEO/__snapshots__/SEO.test.tsx.snap, gatsby/static/robots.txt
https://nicedigital.atlassian.net/browse/CKS-713
=> CKS-713 Add robots txt to prevent generative AI crawlers

functional-tests/README.md, functional-tests/features/cookiesEULA.feature, functional-tests/steps/then.ts, functional-tests/steps/when.ts, functional-tests/support/action/acceptEULA.ts, functional-tests/support/action/cookiesToggle.ts
https://nicedigital.atlassian.net/browse/CKS-738
=> CKS-738 Add new functional automated test for cookies & EULA scenarios

gatsby/package-lock.json, gatsby/package.json, gatsby/src/pages/__tests__/__snapshots__/404.test.tsx.snap
- updating global-nav and design-system with refactored page header updates.
=> CKS-744 : update design-system and global-nav packages

web-app/CKS.Web/web.config
https://nicedigital.atlassian.net/browse/CKS-743
=> CKS-743 Remove X-XSS header from web.config

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-756
=> CKS-756 Bump global nav

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-758
=> CKS-758 Bump global-nav

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-764
=>  CKS-764 Update @nice-digital/design-system to version 5.5.4

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/CKS-767
=> CKS-767 update global nav to latest version with skiplink fix

README.md, fake-api/README.md, functional-tests/README.md, gatsby/README.md, gatsby/plugins/gatsby-source-cks/README.md
https://nicedigital.atlassian.net/browse/CKS-773
=> CKS-773 update readmes to reference `npm ci` over `npm i`
